### PR TITLE
Track playtime and display it in the launcher

### PR DESCRIPTION
**Pull request by NeoFoxxo**
Adds feature requested in #320

### CODE REVIEW

**Comment by NeoFoxxo** [comment]
Now that jak 2 is available I need to distinguish between them and add the playtime on its game page lol

**Comment by xTVaser** [comment]
I took a quick look at this and tried out some things to clean it up, mainly just to show how you can store the time played in the central configuration instead of writing out text files.

I was successful https://github.com/NeoFoxxo/launcher/compare/main...xTVaser:v%252Fwip-improvements but uncovered a weird issue.  The game seems to take 30-40 seconds to start OpenGL:
image

So the process starts immediately but then nothing happens for a while.  I don't really have any ideas why this is happening.

I have this same problem when running your original code as well, so something strange is happening for both of us (or i guess, maybe just me lol)
> actually this seems to happen to me when running the normal project now...might just be me!

**Comment by NeoFoxxo** [comment]
I tested it on my machine and it works perfectly! Now I just got to read the settings file on the front end

**Comment by NeoFoxxo** [comment]
Alright I made a rpc function to send the playtime to the front end and its working for me

**Comment by xTVaser** [comment]
Nice sounds good, yeah my issue was some weird driver issue (even got a BSOD when restarting) completely unrelated.  I'll give it another test soon as well and then this'll probably be good to go.

Thanks for doing the work / waiting around while we got over the jak 2 release hurdle 👍

**Comment by NeoFoxxo** [comment]
Thanks for getting it to save to the settings file I was struggling with that lol. Also sorry about the formatting i probably should've got my prettier to work

**Comment by xTVaser** [comment]
For the frontend you can run `yarn format` and for the backend, I use VSCode with `Rust Analyzer` and it automatically formats on file-save.

**Review by xTVaser — APPROVED** [review]
Looks good to me, I'll let you give it a last once-over since I pushed some more commits cleaning up some of my code.  I also added support for seconds
image
image

**Comment by NeoFoxxo** [comment]
It works fine for me but I think adding seconds makes the UI more cluttered imo, it looks better with just the minutes.

**Comment by xTVaser** [comment]
That's fair, i added them mostly just so i could quickly test and see it working.  I'll revert that portion and merge it then 👍

**Pull request merged**
