### PR TITLE
Mod Source Support Finalization

### PR DESCRIPTION
**Pull request by xTVaser**

### CODE REVIEW

**Comment by dallmeyer** [comment]
- [x] list of mods is not visually filtered by the game page you come from
  - it won't actually install mods that aren't compatible for that game, but it doesn't tell you, it just does nothing
- [x] when installing a mod, its unclear whats happening after clicking mod and before decompile/compile begins (its downloading+extracting release, this could take awhile for mods with custom level/model GLBs)
- [x] already-installed mods are repeated in the available mods section
- [x] ability to update / choose version of mod
- some options operate on vanilla install instead of mod install
  - advanced
    - [x] play in debug mode
    - [x] open REPL
    - [x] decompile
    - [x] compile
    - [x] open game data folder
  - gear icon
    - [x] open settings folder
    - [x] open saves folder
    - [x] copy game executable
    - [x] reset settings
    - [x] uninstall
- [x] search tags as part of 'filter mods'?
- [x] installed mods are filtered by the internal name instead of display name
- [ ] a little clunky that you need to have vanilla installed/up-to-date before you can look at list of mods, but not the end of the world (simpler to ensure we have a copy of iso data for the correct game this way)

fixed a couple of these in https://github.com/open-goal/launcher/pull/534

> Add some basic tracking to mods - number of installs time played progress etc and maybe push it somewhere so we can see what mods are most popular etc.
- [x] This is not done yet in the UI, but this is primarily a mod-source concern.  When the mod-source is grabbing all it's info (from example github releases) it can tally up the download counts and publish that info.  We should do this before finalizing the mod-source schema.

> Discuss/add some way to highlight that a mod has been released/added/new etc.
- [x] Future UX work -- my suggestion, maybe just highlight something that has had it's first release within the last month.  That way there is no state to track and will probably cover 99% of users who are checking back often.

**Comment by xTVaser** [comment]
Do not merge without verifying that going from the old settings.json format file is fine (forwards compatible).

**Comment by dallmeyer** [comment]
https://github.com/user-attachments/assets/0127675c-58a8-409a-996f-6b02bce905d3

**Comment by xTVaser** [comment]
### Testing Notes

Looks good to me, I tested the following things:
- Handles `settings.json` from an existing installation correctly
  - Also handles the removal of unofficial/developer version types (wipes them out and forces the user to pick an official version)
- All the shortcut and directory buttons work
- Installation, updating, etc worked last i checked -- and that stuff has been tested to death by barg and zed so we should be good there.
- Normal installations still works fine

I will follow-up by making sure logs from mods make it into the supp. package.

**Pull request merged**
