### PR TITLE
ci: add Clippy Linter

### LINKED ISSUE #198: Lint backend code in CI
Currently we check rust formatting, but we don't enforce lints.  This is an easy thing we should probably add https://github.com/rust-lang/rust-clippy

### PR DESCRIPTION
**Pull request by SamantaTarun**
Fixes #198 

Currently we check rust formatting, but we don't enforce lints. This is an easy thing we should probably add https://github.com/rust-lang/rust-clippy

### CODE REVIEW

**Comment by xTVaser** [comment]
You should probably debug the build on your fork since I have to manually approve the actions to run every attempt you make.

**Comment by SamantaTarun** [comment]
@xTVaser I am done from my side.

**Comment by xTVaser** [comment]
You should probably just use https://github.com/actions-rs/clippy-check

**Comment by SamantaTarun** [comment]
@xTVaser any changes required? trigger this workflow once.

**Review by xTVaser — APPROVED** [review]
Thanks!, I'll follow up by cleaning up the 2 warnings it found

**Pull request merged**
