### PR TITLE
use unplugin-icons instead of @iconify/svelte

### LINKED ISSUE #281: Switch from iconify to unplugin-icons
Due to a recent bug in development, found out that iconify's icons are not bundled with the app but are instead fetched via an API.

Remove this point of failure and switch to a library that can bundle the icons easily https://github.com/antfu/unplugin-icons

### PR DESCRIPTION
**Pull request by fabjan**
Closes #281

This is what it looked like before on my computer:

Skärmavbild 2023-07-22 kl  15 39 44

This is what it looks like after these changes (I tried to use only Material Design Icons instead of mixing icon sets, but had to dip into "ic" for the Discord icon):

Skärmavbild 2023-07-22 kl  15 50 13

Below are more comparisons to showcase any changes to icons as I picked from the MDI set.

## Texture packs before
Skärmavbild 2023-07-22 kl  15 41 19

## Texture packs after
(note the info icon which replaces an inlined SVG)
Skärmavbild 2023-07-22 kl  16 01 02

## Progress before
Skärmavbild 2023-07-22 kl  15 47 39
Skärmavbild 2023-07-22 kl  15 48 53

## Progress after
Skärmavbild 2023-07-22 kl  14 48 27
Skärmavbild 2023-07-22 kl  14 49 39

## Help after
Skärmavbild 2023-07-22 kl  15 15 09

## Version list after
Skärmavbild 2023-07-22 kl  15 26 19
Skärmavbild 2023-07-22 kl  15 28 25

### CODE REVIEW

**Comment by xTVaser** [comment]
hmm this overlap seems odd, is that something new or something you've always seen in your environment? (I've yet to run the launcher on mac)
image

**Review by xTVaser — CHANGES_REQUESTED** [review]
You'll want to add a `src/app.d.ts` file with the following:
```js
/// <reference types="unplugin-icons/types/svelte" />
```
to get rid of typescript errors around the `~icon...` imports

**Comment by fabjan** [comment]
> hmm this overlap seems odd, is that something new or something you've always seen in your environment? (I've yet to run the launcher on mac)
> image

I don't recall it from my last PR, but as you can see it's there both before and after my changes. The before screenshots were taken by checking out `main`, running `yarn install`, and running `yarn tauri dev` to restart the app.

Maybe it's because of the version I have installed, it has a longish name with the architecture etc. and I didn't have one installed before I think.

**Comment by xTVaser** [comment]
Yeah, it could also be because of a recent dependency bump

**Comment by fabjan** [comment]
> Maybe it's because of the version I have installed, it has a longish name with the architecture etc. and I didn't have one installed before I think.

Yeah if I remove the version there is no overlap.

**Comment by xTVaser** [comment]
Ah ok I see what you're saying, yeah i can reproduce on my end as well -- just some bad CSS then if the lines are too long.

image

**Comment by fabjan** [comment]
I tried with an overflow-hidden class on the active version text paragraph, but that didn't make a difference. It seems like the first flex item is the problem, not the longer text per se?

Here are the flex things in the header that are messing up:

Skärmavbild 2023-07-22 kl  20 53 05
Skärmavbild 2023-07-22 kl  20 52 17
Skärmavbild 2023-07-22 kl  20 52 32
Skärmavbild 2023-07-22 kl  20 52 43

**Review by xTVaser — APPROVED** [review]

**Pull request merged**
